"""Epistemic bookkeeping for the trading brain.

The single most important invariant in this system: every number, claim and
statement that leaves an engine carries an explicit *evidence class*. Nothing is
allowed to silently change class. A source claim never becomes a fact by being
repeated; a model estimate never becomes a market price; a backtest result never
becomes a prediction.

Everything in ``tradingbrain`` that produces a user-visible assertion returns (or
embeds) a :class:`Claim`.
"""

from __future__ import annotations

import dataclasses
import datetime as _dt
import enum
import json
from typing import Any, Iterable, Mapping


class EvidenceClass(str, enum.Enum):
    """The six categories the operator requires to be kept distinct."""

    SOURCE_FACT = "SOURCE_FACT"
    """Something a named source verifiably *said*. Not a claim that it is true."""

    INFERENCE = "INFERENCE"
    """A logical step this system took from source material or from data."""

    HYPOTHESIS = "HYPOTHESIS"
    """A testable proposition that has not (yet) been tested."""

    BACKTEST_RESULT = "BACKTEST_RESULT"
    """Output of a simulation over historical data, under stated assumptions."""

    LIVE_MARKET_OBSERVATION = "LIVE_MARKET_OBSERVATION"
    """A measurement of actual market data as of a stated timestamp."""

    MODEL_ESTIMATE = "MODEL_ESTIMATE"
    """Output of a pricing/statistical model. Never a market price."""


#: Human-readable, deliberately deflationary descriptions used in the UI.
EVIDENCE_DESCRIPTIONS: Mapping[str, str] = {
    EvidenceClass.SOURCE_FACT: (
        "A source said this. Recording it does not make it true; it makes it testable."
    ),
    EvidenceClass.INFERENCE: (
        "A reasoning step taken by this system. Check the premises before relying on it."
    ),
    EvidenceClass.HYPOTHESIS: (
        "An untested proposition. No evidential weight until an experiment runs."
    ),
    EvidenceClass.BACKTEST_RESULT: (
        "Simulated on historical data under stated assumptions. Past simulation, not a forecast."
    ),
    EvidenceClass.LIVE_MARKET_OBSERVATION: (
        "A measurement of market data at a stated timestamp from a stated provider."
    ),
    EvidenceClass.MODEL_ESTIMATE: (
        "Produced by a model from stated inputs. Not a quoted or executable price."
    ),
}


class DataOrigin(str, enum.Enum):
    """Where the underlying bars came from. Surfaced everywhere downstream."""

    REAL = "REAL"
    """Vendor market data."""

    SYNTHETIC = "SYNTHETIC"
    """Generated by this repository for development/testing. Never tradeable."""

    UNKNOWN = "UNKNOWN"


@dataclasses.dataclass(frozen=True)
class SourceRef:
    """Pointer back to where a piece of knowledge came from."""

    source: str
    url: str | None = None
    author: str | None = None
    date: str | None = None
    title: str | None = None
    source_type: str | None = None
    retrieval_method: str | None = None
    fulltext_verified: bool = False
    note: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass
class Claim:
    """An assertion plus everything needed to audit it."""

    statement: str
    evidence: EvidenceClass
    value: Any = None
    sample_size: int | None = None
    period: str | None = None
    definition_of_success: str | None = None
    data_source: str | None = None
    data_origin: DataOrigin = DataOrigin.UNKNOWN
    methodology: str | None = None
    confidence_interval: tuple[float, float] | None = None
    caveats: list[str] = dataclasses.field(default_factory=list)
    sources: list[SourceRef] = dataclasses.field(default_factory=list)
    created_at: str = dataclasses.field(
        default_factory=lambda: _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    )

    # -- guards -------------------------------------------------------------
    def __post_init__(self) -> None:
        self.evidence = EvidenceClass(self.evidence)
        self.data_origin = DataOrigin(self.data_origin)
        if self.evidence in (
            EvidenceClass.BACKTEST_RESULT,
            EvidenceClass.LIVE_MARKET_OBSERVATION,
        ) and self.data_source is None:
            raise ValueError(
                f"{self.evidence.value} claims must name a data source: {self.statement!r}"
            )
        if self.data_origin is DataOrigin.SYNTHETIC:
            marker = "Derived from SYNTHETIC data. Not evidence about real markets."
            if marker not in self.caveats:
                self.caveats.append(marker)

    def to_dict(self) -> dict[str, Any]:
        d = dataclasses.asdict(self)
        d["evidence"] = self.evidence.value
        d["data_origin"] = self.data_origin.value
        d["evidence_meaning"] = EVIDENCE_DESCRIPTIONS[self.evidence]
        return d

    def render(self) -> str:
        """Plain-text rendering that always carries the qualifiers."""
        bits = [f"[{self.evidence.value}] {self.statement}"]
        if self.sample_size is not None:
            bits.append(f"N = {self.sample_size}")
        if self.confidence_interval is not None:
            lo, hi = self.confidence_interval
            bits.append(f"95% CI [{lo:.4g}, {hi:.4g}]")
        if self.period:
            bits.append(f"period: {self.period}")
        if self.data_source:
            bits.append(f"data: {self.data_source} ({self.data_origin.value})")
        if self.methodology:
            bits.append(f"method: {self.methodology}")
        for c in self.caveats:
            bits.append(f"caveat: {c}")
        return " | ".join(bits)


def proportion_statement(successes: int, n: int, horizon: str, criterion: str) -> str:
    """Phrase a proportion the way the operator demanded it be phrased.

    Never "63.4% chance"; always "63.4% of the 428 qualifying events ...".
    """
    if n <= 0:
        return f"No qualifying events found for {criterion} over {horizon}."
    pct = 100.0 * successes / n
    return (
        f"{pct:.1f}% of the {n} historical qualifying events {criterion} "
        f"over {horizon}."
    )


def bundle(claims: Iterable[Claim]) -> list[dict[str, Any]]:
    return [c.to_dict() for c in claims]


def to_json(obj: Any) -> str:
    def _default(o: Any) -> Any:
        if isinstance(o, Claim):
            return o.to_dict()
        if isinstance(o, (SourceRef,)):
            return o.to_dict()
        if isinstance(o, enum.Enum):
            return o.value
        if dataclasses.is_dataclass(o):
            return dataclasses.asdict(o)
        if isinstance(o, (_dt.date, _dt.datetime)):
            return o.isoformat()
        raise TypeError(f"not serialisable: {type(o)!r}")

    return json.dumps(obj, default=_default, indent=2, sort_keys=False)
